name: yolov7_bytetrack
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - cython=0.29.30
  - ffmpeg=4.2.2
  - numpy=1.23.1
  - numpy-base=1.23.1
  - pytorch=1.12.1
  - pytorch-mutex=1.0
  - setuptools=63.4.1
  - streamlit=1.11.0
  - torchvision=0.13.1
  - tqdm=4.64.0
  - wheel=0.37.1
  - yaml=0.2.5
  - pip:
    - click==8.1.3
    - coloredlogs==15.0.1
    - easydict==1.9
    - gdown==4.5.1
    - lap==0.4.0
    - matplotlib==3.5.3
    - onnxruntime-gpu==1.12.1
    - opencv-python==4.6.0.66
    - pycocotools==2.0.4
    - pytz==2022.2.1
    - pyyaml==6.0
    - scipy==1.9.1
    - tensorboard==2.10.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - urllib3==1.26.12